version: "3.8"

services:
  gateway:
    image: ${DOCKER_REGISTRY-}gateway
    build:
      context: .
      dockerfile: gateway/Dockerfile
    restart: unless-stopped
    ports:
      - "4343:80"
    environment:
      PORT: "80"
      ORGANIZATION_GRAPHQL_API: http://organization-api/graphql
    profiles:
      - gateway
      - all
    networks:
      - connectilly_network
