-- create "organizations" table
CREATE TABLE "organizations" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying NULL, PRIMARY KEY ("id"));
-- create index "organization_name" to table: "organizations"
CREATE INDEX "organization_name" ON "organizations" ("name");
