// Code generated by go-connectilly-event-template, DO NOT EDIT.

package organizationv1

//go:generate mockgen -source=consumer_eventgen.go -destination=mock/consumer_eventgen_gen.go
//go:generate mockgen -source=handler_eventgen.go -destination=mock/handler_eventgen_gen.go
//go:generate mockgen -source=producer_eventgen.go -destination=mock/producer_eventgen_gen.go
