
// Code generated by go-connectilly-event-template, DO NOT EDIT.

package organizationv1

import (
	"context"
)

type Subscriber interface {
  Handle(ctx context.Context, event OrganizationEvent) error
}
