
// Code generated by go-connectilly-event-template, DO NOT EDIT.

package organizationv1

import (
    
      "encoding/json"
      "fmt"
    
      "time"
    
      "github.com/google/uuid"
    )
    
    // OrganizationEvent represents a OrganizationEvent model.
type OrganizationEvent struct {
  Metadata Metadata `json:"metadata"` 
  Data Data `json:"data"` 
}
    
    
    // Metadata represents a Metadata model.
type Metadata struct {
  Id uuid.UUID `json:"id"`  // The unique message ID
  Source string `json:"source"` 
  EventType EventType `json:"eventType"` 
  Subject string `json:"subject"` 
  Time time.Time `json:"time"` 
  CorrelationId uuid.UUID `json:"correlationId"` 
  Actor string `json:"actor"` 
}
    
    
    // EventType represents an enum of EventType.
type EventType uint

const (
  EventTypeOrganizationCreated EventType = iota
  EventTypeOrganizationUpdated
)

// Value returns the value of the enum.
func (op EventType) Value() any {
	if op >= EventType(len(EventTypeValues)) {
		return nil
	}
	return EventTypeValues[op]
}

var EventTypeValues = []any{"organizationCreated","organizationUpdated"}
var ValuesToEventType = map[any]EventType{
  EventTypeValues[EventTypeOrganizationCreated]: EventTypeOrganizationCreated,
  EventTypeValues[EventTypeOrganizationUpdated]: EventTypeOrganizationUpdated,
}

    
    
    // Data represents a Data model.
type Data struct {
  BeforeState *Organization `json:"beforeState,omitempty"` 
  AfterState Organization `json:"afterState"` 
}
    
    
    // Organization represents a Organization model.
type Organization struct {
  Id int `json:"id"`  // The unique organization ID
  Name *string `json:"name,omitempty"`  // The organization name
  AdditionalProperties *map[string]interface{} `json:"additionalProperties,omitempty"` 
}
    
func (enumVal EventType) MarshalJSON() ([]byte, error) {
  return json.Marshal(enumVal.String())
}

func (enumVal EventType) String() string {
  return fmt.Sprintf("%v", EventTypeValues[int(enumVal)])
}

func (enumVal *EventType) UnmarshalJSON(buffer []byte) error {
  var str string
  if err := json.Unmarshal(buffer, &str); err != nil {
    return err
  }

  var tmpEnumVal EventType
  var ok bool

  if tmpEnumVal, ok = ValuesToEventType[str]; !ok {
    return fmt.Errorf("unknown %s", str)
  }

  *enumVal = tmpEnumVal

  return nil
}
