// Code generated by connectillyctl, DO NOT EDIT.

package v1

import (
	"context"

	"github.com/Connectilly/connectilly/src/shared/enterprise/messaging"
	"go.uber.org/zap"
	"google.golang.org/protobuf/proto"
)

type Producer interface {
	Produce(ctx context.Context, key string, event Event) error
	Close()
}

type producer struct {
	logger          *zap.SugaredLogger
	messageProducer messaging.MessageProducer
}

func NewProducer(
	logger *zap.SugaredLogger,
	messageProducer messaging.MessageProducer) Producer {
	return &producer{
		logger:          logger,
		messageProducer: messageProducer,
	}
}

func (c *producer) Produce(ctx context.Context, key string, event Event) error {
	data, err := proto.Marshal(&event)
	if err != nil {
		c.logger.Errorf(
			"Failed to serialize Event message to Protobuf byte array. Error: %v",
			err)

		return err
	}

	if err := c.messageProducer.Connect(TopicName); err != nil {
		return err
	}

	if err := c.messageProducer.Produce(ctx, key, data); err != nil {
		return err
	}

	return nil
}

func (c *producer) Close() {
	c.messageProducer.Close()
}
