
// Code generated by go-connectilly-event-template, DO NOT EDIT.

package organizationv1

import (
	"context"
	"encoding/json"

	"github.com/Connectilly/connectilly/src/shared/enterprise/messaging"
	"go.uber.org/zap"
)

type Producer interface {
	Produce(ctx context.Context, key string, event OrganizationEvent) error
	Close()
}

type producer struct {
	logger          *zap.SugaredLogger
	messageProducer messaging.MessageProducer
}

func NewProducer(
	logger *zap.SugaredLogger,
	messageProducer messaging.MessageProducer) Producer {
	return &producer{
		logger:          logger,
		messageProducer: messageProducer,
	}
}

func (c *producer) Produce(ctx context.Context, key string, event OrganizationEvent) error {
	data, err := json.Marshal(event)
	if err != nil {
		c.logger.Errorf(
			"Failed to serialize OrganizationEvent message to json. Error: %v",
			err)

		return err
	}

	if err := c.messageProducer.Connect(TopicName); err != nil {
		return err
	}

	if err := c.messageProducer.Produce(ctx, key, data); err != nil {
		return err
	}

	return nil
}

func (c *producer) Close() {
	c.messageProducer.Close()
}
