// Code generated by MockGen. DO NOT EDIT.
// Source: client_event_metadata_generator_service.go

// Package mock_generators is a generated GoMock package.
package mock_generators

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClientEventMetadataGeneratorService is a mock of ClientEventMetadataGeneratorService interface.
type MockClientEventMetadataGeneratorService struct {
	ctrl     *gomock.Controller
	recorder *MockClientEventMetadataGeneratorServiceMockRecorder
}

// MockClientEventMetadataGeneratorServiceMockRecorder is the mock recorder for MockClientEventMetadataGeneratorService.
type MockClientEventMetadataGeneratorServiceMockRecorder struct {
	mock *MockClientEventMetadataGeneratorService
}

// NewMockClientEventMetadataGeneratorService creates a new mock instance.
func NewMockClientEventMetadataGeneratorService(ctrl *gomock.Controller) *MockClientEventMetadataGeneratorService {
	mock := &MockClientEventMetadataGeneratorService{ctrl: ctrl}
	mock.recorder = &MockClientEventMetadataGeneratorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientEventMetadataGeneratorService) EXPECT() *MockClientEventMetadataGeneratorServiceMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockClientEventMetadataGeneratorService) Generate(packageName, topicName, outputPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", packageName, topicName, outputPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockClientEventMetadataGeneratorServiceMockRecorder) Generate(packageName, topicName, outputPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockClientEventMetadataGeneratorService)(nil).Generate), packageName, topicName, outputPath)
}
