// Code generated by MockGen. DO NOT EDIT.
// Source: client_event_consumer_generator_service.go

// Package mock_generators is a generated GoMock package.
package mock_generators

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClientEventConsumerGeneratorService is a mock of ClientEventConsumerGeneratorService interface.
type MockClientEventConsumerGeneratorService struct {
	ctrl     *gomock.Controller
	recorder *MockClientEventConsumerGeneratorServiceMockRecorder
}

// MockClientEventConsumerGeneratorServiceMockRecorder is the mock recorder for MockClientEventConsumerGeneratorService.
type MockClientEventConsumerGeneratorServiceMockRecorder struct {
	mock *MockClientEventConsumerGeneratorService
}

// NewMockClientEventConsumerGeneratorService creates a new mock instance.
func NewMockClientEventConsumerGeneratorService(ctrl *gomock.Controller) *MockClientEventConsumerGeneratorService {
	mock := &MockClientEventConsumerGeneratorService{ctrl: ctrl}
	mock.recorder = &MockClientEventConsumerGeneratorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientEventConsumerGeneratorService) EXPECT() *MockClientEventConsumerGeneratorServiceMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockClientEventConsumerGeneratorService) Generate(packageName, eventType, outputPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", packageName, eventType, outputPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockClientEventConsumerGeneratorServiceMockRecorder) Generate(packageName, eventType, outputPath interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockClientEventConsumerGeneratorService)(nil).Generate), packageName, eventType, outputPath)
}
