// Code generated by ent, DO NOT EDIT.

//go:build tools
// +build tools

// Package internal holds a loadable version of the latest schema.
package internal

const Schema = `{"Schema":"github.com/Connectilly/connectilly/src/organization/shared/entities/schema","Package":"github.com/Connectilly/connectilly/src/organization/shared/entities","Schemas":[{"name":"Organization","config":{"Table":""},"fields":[{"name":"name","type":{"Type":7,"Ident":"","PkgPath":"","PkgName":"","Nillable":false,"RType":null},"optional":true,"position":{"Index":0,"MixedIn":false,"MixinIndex":0},"annotations":{"EntGQL":{"OrderField":"name"}}}],"indexes":[{"fields":["name"]}]}],"Features":["privacy","intercept","entql","namedges","schema/snapshot","sql/schemaconfig","sql/lock","sql/modifier","sql/execquery","sql/upsert","sql/versioned-migration","namedges"]}`
