version: "3.8"

networks:
  connectilly_network:


volumes:
  connectilly_pulsar_data:
  connectilly_cockroachdb_data:


services:
  dozzle:
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9999:8080
    profiles:
      - core
      - organization
      - gateway
      - all
    networks:
      - connectilly_network

  cockroachdb:
    image: cockroachdb/cockroach:latest-v22.2
    ports:
      - "26257:26257"
      - "8080:8080"
    command: start-single-node --insecure
    volumes:
      - connectilly_cockroachdb_data:/cockroach/cockroach-data"
    profiles:
      - core
      - organization
      - gateway
      - all
    networks:
      - connectilly_network
