// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

import (
	"github.com/Connectilly/connectilly/src/organization/shared/entities"
)

type CreateOrganizationInput struct {
	ClientMutationID *string `json:"clientMutationId"`
	Name             string  `json:"name"`
}

type OrganizationPayload struct {
	ClientMutationID *string                `json:"clientMutationId"`
	Organization     *entities.Organization `json:"organization"`
}
